{
 "title": "COVID-19",
 "time": { "from": "now-2M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "continent_name",
    "query": "SELECT continent_name FROM time_series_per_continent"
   },
   {
    "name": "country_name",
    "query": "SELECT country_name FROM time_series_per_country"
   }
  ]
 },
 "panels": [
  {
   "title": "Country Stats - Latest",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  active AS \"Active\",\n  confirmed AS \"Confirmed\" ,\n  recovered AS \"Recovered\",\n  deaths AS \"Deaths\" \nFROM time_series_per_country_latest\nWHERE\n  country_name in ($country_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Cases Per Country Per Million (Latest)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  active AS \"Active\",\n  confirmed AS \"Confirmed\" ,\n  recovered AS \"Recovered\",\n  deaths AS \"Deaths\" \nFROM time_series_per_country_per_million\nWHERE\n  country_name in ($country_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Cases Per Country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  active AS \"Active\",\n  deaths AS \"Deaths\",\n  confirmed AS \"Confirmed\",\n  recovered AS \"Recovered\"\nFROM time_series_per_country\nWHERE\n  $__timeFilter(\"timestamp\")\nAND country_name in ($country_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Fatality Rate",
   "type": "stat",
   "description": "Fatality Rate Calculated against Death and Confirmed Cases",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  (deaths::decimal / confirmed::decimal) * 100 AS \"Fatality Rate\"\nFROM time_series_per_country_latest\nWHERE\n  country_name in ($country_name)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cases Per Country - New Cases (Daily Changes)",
   "type": "graph",
   "description": "Each day shows cases reported since the previous day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  new_active AS \"New Active\",\n  new_deaths AS \"New Deaths\",\n  new_confirmed AS \"New Confirmed\",\n  new_recovered AS \"New Recovered\"\nFROM time_series_per_country\nWHERE\n  $__timeFilter(\"timestamp\")\nAND country_name in ($country_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "stat",
   "description": "Recovery Rate Calculated against Recovered and Confirmed Cases",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  (recovered::decimal / confirmed::decimal) * 100 AS \"Fatality Rate\"\nFROM time_series_per_country_latest\nWHERE\n  country_name in ($country_name)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Continent Stats - Latest",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  continent_name AS \"Title\",\n  active AS \"Active\",\n  confirmed AS \"Confirmed\" ,\n  recovered AS \"Recovered\",\n  deaths AS \"Deaths\" \nFROM time_series_per_continent_latest\nWHERE\n  continent_name in ($continent_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Incidence Per Country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  incidence AS \"Incidence\"\nFROM time_series_per_country_incidence\nWHERE\n  $__timeFilter(\"timestamp\")\nAND country_name in ($country_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Global Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  active AS \"Active\",\n  deaths AS \"Deaths\",\n  confirmed AS \"Confirmed\",\n  recovered AS \"Recovered\"\nFROM time_series_global\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Cases Per Country Per Million",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  country_name AS \"Title\",\n  active AS \"Active\",\n  deaths AS \"Deaths\",\n  confirmed AS \"Confirmed\",\n  recovered AS \"Recovered\"\nFROM time_series_per_country_per_million\nWHERE\n  $__timeFilter(\"timestamp\")\nAND country_name in ($country_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Global Stats - Latest",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  active AS \"Active\",\n  confirmed AS \"Confirmed\" ,\n  recovered AS \"Recovered\",\n  deaths AS \"Deaths\" \nFROM time_series_global\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Cases Per Continent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  continent_name AS \"Title\",\n  active AS \"Active\",\n  deaths AS \"Deaths\",\n  confirmed AS \"Confirmed\",\n  recovered AS \"Recovered\"\nFROM time_series_per_continent\nWHERE\n  $__timeFilter(\"timestamp\")\nAND continent_name in ($continent_name)\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Global - New Cases (Daily Changes)",
   "type": "graph",
   "description": "Each day shows cases reported since the previous day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  new_active AS \"New Active\",\n  new_deaths AS \"New Deaths\",\n  new_confirmed AS \"New Confirmed\",\n  new_recovered AS \"New Recovered\"\nFROM time_series_global\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Cases Per Continent - New Cases (Daily Changes)",
   "type": "graph",
   "description": "Each day shows cases reported since the previous day",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  continent_name AS \"Title\",\n  new_active AS \"New Active\",\n  new_deaths AS \"New Deaths\",\n  new_confirmed AS \"New Confirmed\",\n  new_recovered AS \"New Recovered\"\nFROM time_series_per_continent\nWHERE\n  $__timeFilter(\"timestamp\")\nAND continent_name in ($continent_name)\nORDER BY 1\n"
    }
   ]
  }
 ]
}